### ISSUE TITLE
util.py is in gitignore?

### ISSUE THREAD

**Issue by harkmug** [McHughes288/emotion_detection_cpc#1]
Hi John,

Great work, eager to try it out! 

Was curious if the [various calls to util](https://github.com/McHughes288/emotion_detection_cpc/search?q=util&unscoped_q=util) require util.py to be in the repo (seems to be [in gitignore at present](https://github.com/McHughes288/emotion_detection_cpc/blob/c99110e661fd58e34bca77c0fa28753ec953a267/.gitignore#L10))?

Thanks!

**Comment by jplhughes** [comment]
Hi,

Thanks for your interest! A couple of the files need a bit of work before I commit them. I'll try find some time soon to get them in shape. 

To get the code working right now, you'll have to write your own dataloader and replace or delete some of the functions imported from util. The rest of the code for training models is all there.

Cheers,
John

**Comment by jplhughes** [comment]
util.py has now been added
