### ISSUE TITLE
miss util fold

### ISSUE THREAD

**Issue by TythonLee** [McHughes288/emotion_detection_cpc#2]
Hi John,
I want to reproduce your emotion_detection_cpc project, but I found that the util fold is missing when import util in cpc/train.py. The librispeech process code is missing as well.

**Comment by jplhughes** [comment]
Hi @TythonLee,

I haven't had time to get util.py and the dataloading in shape unfortunately - some of the code I can't upload to my personal github. I plan to add this soon. However, the CPC and training code is fully functional so you can use that as reference in your own project when reproducing. As for Librispeech it can be downloaded here: http://www.openslr.org/12.

Let me know if you have any other issues and I'll be happy to help.

Cheers,
John

**Comment by jplhughes** [comment]
util.py now added, hope that helps!

**Comment by jplhughes** [comment]
Work in progress dataloader on this branch should get you going properly now: https://github.com/McHughes288/emotion_detection_cpc/tree/feature/include_dataloader

To get librispeech working just create a train.dbl, and val.dbl which is just a list of the filenames (one per line).
